---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-herokuapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: app-heroku
      version: blue
  template:
    metadata:
      name: web-herokuapp-pod
      labels:
        app: app-heroku
        version: blue
    spec:
      containers:
      - name: web-herokuapp-container
        image: 3.136.118.102:5000/repo_entelgy:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 80
