---
- name: playbook to deploy on kubernetes
  hosts: ec2
  become: yes
  tasks:
    - name: copy deployment file to kubernetes master
      copy:
        src: deployment.yml
        dest: /u01/kubernetes/
 #   - name: delete deployment file in kubernetes master
 #     command: kubectl delete -f /u01/kubernetes/deployment.yml
    - name: create deployment file in kubernetes master
      command: kubectl apply -f /u01/kubernetes/deployment.yml
        
