---
- name: playbook run command
  hosts: ec2
  become: yes
  tasks:
    - name: run command
      command: cat /etc/hostname
      register: result_hostname
    - debug:
        var=result_hostname
